MAINT: Handle warnings in tutorials
numpy/numpy-tutorials pull request #203
Opened 2024-01-13 00:56 UTC by rossbar

General maintenance to remove warnings from running the notebooks, including handling deprecated functions in scipy, which just released and rc for 1.12.

As noted in #154, failing on runtime warnings is not currently baked into CI. The way that I did this locally was to convert the tutorials into pure python files:

```bash
$ cd content
$ jupytext *.md --from myst --to py
```

Then run each of the python files with `-Werror`:

```bash
$ find content/ -name "*.py" -exec python -Werror {} \;
```

It's not *perfect*, but maybe something along these lines could be added to CI to resolve #154

2024-01-13 22:15 UTC, bsipocz requested changes
We need to deal with the oldest supported scipy version, otherwise this looks good to me.

2024-01-13 22:15 UTC, bsipocz commented on content/tutorial-svd.md
> +from scipy import datasets
If we are committed to do SPEC0 type version support, then cannot yet do this change as `datasets` was added in 1.10 and we're still on 1.8 as oldest scipy

```suggestion
try:
    from scipy.datasets import face
except ImportError:
    from scipy.misc import face
```

2024-01-13 22:15 UTC, bsipocz commented on content/tutorial-svd.md
> +img = datasets.face()
In additon to the previous change, GH didn't let me do only one suggestion due to the deleted line in the diff
```suggestion
img =face()
```

2024-01-17 07:11 UTC, rossbar commented
> We need to deal with the oldest supported scipy version, otherwise this looks good to me.

Good point - though I think there's a broader discussion to be had here. IMO the most important thing is supporting the latest releases. I'm not sure there's as much value in supporting the oldest devs.

2024-01-18 18:48 UTC, bsipocz commented
> I'm not sure there's as much value in supporting the oldest devs.

I'm thinking mostly about end users who may stuck on older systems without the ability (or in fact the need) to upgrade versions to try to run a tutorial. Not sure how much this is a real concern.

2024-01-18 21:27 UTC, rossbar commented
> I'm thinking mostly about end users who may stuck on older systems without the ability (or in fact the need) to upgrade versions to try to run a tutorial. Not sure how much this is a real concern.

Yeah that's a good point, and it jives with some of the other unofficial policies that the tutorials have adopted; e.g. not using sphinx-specific features (like intersphinx) in the tutorials themselves so they're still 100% functional as standalone notebooks. There's definitely a wider discussion to be had :)

2024-01-19 06:23 UTC, bsipocz commented
What about getting in the try/except to make the current CI setup happy, and then discussing what would be sensible to do down the road?

2024-01-19 17:36 UTC, bsipocz approved these changes
Now it all looks good, thank you!

Maybe open an issue about the minimum scipy version, etc policies, so we don't forget to actually have the discussion :)

2024-01-20 04:22 UTC, rossbar commented on content/x_y-squared.npz
Yeah, I must've caught it in a `git commit -a`. The file is already tracked, but it definitely shouldn't be. I'll make sure to back out the "changes" to the file here. We should remove it entirely from being tracked in a separate PR IMO.

2024-01-22 20:00 UTC, bsipocz commented on content/x_y-squared.npz
I got bitten early on with `git commit -a` when working with submodules that I never use it ever :)

2024-01-22 20:00 UTC, merged

2024-01-22 20:00 UTC, bsipocz commented
Thanks @rossbar!